export interface MetActivity {
  name: string;
  low: number;
  med: number;
  high: number;
}

export const MET_ACTIVITIES: MetActivity[] = [
  { name: "Aeróbica", low: 3.5, med: 5.0, high: 7.3 },
  { name: "Artes marciales", low: 5.3, med: 7.0, high: 10.3 },
  { name: "Artes marciales combinadas", low: 6.0, med: 9.0, high: 12.0 },
  { name: "Bádminton", low: 4.5, med: 5.5, high: 7.0 },
  { name: "Baile", low: 3.3, med: 5.0, high: 7.0 },
  { name: "Baile floss", low: 3.0, med: 4.5, high: 6.0 },
  { name: "Básquetbol", low: 4.5, med: 6.0, high: 8.0 },
  { name: "Béisbol", low: 3.0, med: 4.0, high: 5.0 },
  { name: "Biatlón", low: 7.0, med: 10.5, high: 13.5 },
  { name: "Bicicleta", low: 4.0, med: 8.0, high: 10.0 },
  { name: "Bicicleta fija", low: 3.5, med: 6.0, high: 8.5 },
  { name: "Boxeo", low: 5.5, med: 7.0, high: 12.8 },
  { name: "Buceo", low: 4.0, med: 7.0, high: 10.0 },
  { name: "Calistenia", low: 3.5, med: 5.0, high: 8.0 },
  { name: "Caminata", low: 2.5, med: 3.5, high: 4.5 },
  { name: "Caminata a ritmo rápido", low: 3.8, med: 5.0, high: 6.5 },
  { name: "Caminata con un carrito para niños", low: 3.0, med: 4.0, high: 5.0 },
  { name: "Caminata en la cinta", low: 2.5, med: 3.8, high: 5.0 },
  { name: "Caminata nórdica", low: 3.0, med: 4.8, high: 6.0 },
  { name: "Caminata rápida", low: 3.8, med: 5.0, high: 6.5 },
  { name: "Ciclismo de montaña", low: 5.5, med: 8.5, high: 14.0 },
  { name: "Ciclismo de ruta", low: 6.0, med: 9.0, high: 12.0 },
  { name: "Ciclismo manual", low: 3.0, med: 5.0, high: 7.5 },
  { name: "Ciclismo urbano", low: 4.0, med: 6.8, high: 10.0 },
  { name: "Circuito de entrenamiento", low: 4.0, med: 6.0, high: 8.0 },
  { name: "Clavadismo", low: 3.0, med: 4.0, high: 5.0 },
  { name: "Correr", low: 7.0, med: 10.0, high: 15.0 },
  { name: "Correr en cinta", low: 7.0, med: 9.8, high: 14.0 },
  { name: "Correr en la arena", low: 8.0, med: 11.5, high: 16.0 },
  { name: "Críquet", low: 3.0, med: 4.8, high: 6.0 },
  { name: "Crossfit", low: 5.0, med: 8.0, high: 12.0 },
  { name: "Curling", low: 2.5, med: 3.5, high: 4.5 },
  { name: "Elíptico", low: 4.5, med: 7.0, high: 10.0 },
  { name: "Entrenamiento de fuerza", low: 3.0, med: 5.0, high: 6.0 },
  { name: "Entrenamiento por intervalos", low: 4.5, med: 7.0, high: 10.0 },
  { name: "Entrenamiento por intervalos intenso", low: 6.0, med: 9.5, high: 13.0 },
  { name: "Equitación", low: 3.0, med: 5.5, high: 8.0 },
  { name: "Escalada", low: 5.0, med: 8.0, high: 11.0 },
  { name: "Escalador", low: 4.5, med: 7.5, high: 10.0 },
  { name: "Esgrima", low: 4.0, med: 6.0, high: 8.0 },
  { name: "Esquí", low: 4.5, med: 7.0, high: 9.5 },
  { name: "Esquí con raquetas de nieve", low: 5.0, med: 8.0, high: 11.0 },
  { name: "Esquí cuesta abajo", low: 4.0, med: 6.0, high: 8.0 },
  { name: "Esquí de fondo", low: 5.5, med: 9.0, high: 12.5 },
  { name: "Freeride", low: 5.0, med: 7.5, high: 10.0 },
  { name: "Frisbee", low: 3.0, med: 4.0, high: 5.0 },
  { name: "Fútbol", low: 5.0, med: 7.0, high: 10.0 },
  { name: "Fútbol americano", low: 4.5, med: 7.0, high: 9.0 },
  { name: "Fútbol australiano", low: 5.0, med: 7.5, high: 10.5 },
  { name: "Gimnasia", low: 3.0, med: 4.0, high: 6.0 },
  { name: "Golf", low: 2.5, med: 3.5, high: 4.5 },
  { name: "Handball", low: 5.0, med: 8.0, high: 11.0 },
  { name: "Hockey", low: 5.0, med: 7.8, high: 10.0 },
  { name: "Hyrox", low: 6.0, med: 9.0, high: 13.0 },
  { name: "Jardinería", low: 2.5, med: 3.8, high: 5.0 },
  { name: "Kayakismo", low: 3.0, med: 5.0, high: 8.0 },
  { name: "Kickboxing", low: 5.5, med: 8.0, high: 11.5 },
  { name: "Kite esquí", low: 5.0, med: 7.5, high: 10.0 },
  { name: "Kitesurf", low: 5.0, med: 7.8, high: 11.0 },
  { name: "Levantamiento de pesas", low: 3.0, med: 5.0, high: 6.0 },
  { name: "Máquina de ejercicios", low: 3.0, med: 4.5, high: 6.0 },
  { name: "Máquina de remo", low: 3.5, med: 6.0, high: 8.5 },
  { name: "Meditación", low: 1.0, med: 1.2, high: 1.5 },
  { name: "Monopatín", low: 3.0, med: 5.0, high: 6.5 },
  { name: "Natación", low: 5.3, med: 8.0, high: 10.0 },
  { name: "Natación en aguas abiertas", low: 6.0, med: 8.5, high: 11.0 },
  { name: "Natación en piscinas", low: 5.0, med: 7.5, high: 9.5 },
  { name: "Otro", low: 3.0, med: 5.0, high: 7.0 },
  { name: "P90x", low: 5.5, med: 7.8, high: 10.5 },
  { name: "Parapente", low: 2.0, med: 2.8, high: 3.5 },
  { name: "Patinaje", low: 4.0, med: 6.0, high: 8.0 },
  { name: "Patinaje en línea", low: 4.5, med: 7.0, high: 9.8 },
  { name: "Patinaje en pista cubierta", low: 4.0, med: 6.5, high: 8.5 },
  { name: "Patinaje nórdico", low: 5.0, med: 7.5, high: 10.5 },
  { name: "Patinaje sobre hielo", low: 3.5, med: 5.5, high: 7.5 },
  { name: "Pesas rusas", low: 4.0, med: 7.0, high: 9.5 },
  { name: "Pilates", low: 2.5, med: 3.5, high: 5.0 },
  { name: "Polo", low: 4.0, med: 6.0, high: 8.0 },
  { name: "Polo acústico", low: 3.0, med: 4.5, high: 6.0 },
  { name: "Ráquetbol", low: 5.0, med: 7.5, high: 10.0 },
  { name: "Remo", low: 3.5, med: 6.0, high: 8.5 },
  { name: "Rugby", low: 5.0, med: 8.0, high: 11.0 },
  { name: "Saltar la cuerda", low: 8.0, med: 11.0, high: 14.0 },
  { name: "Senderismo", low: 3.5, med: 6.0, high: 9.0 },
  { name: "Silla de ruedas", low: 3.0, med: 4.5, high: 6.5 },
  { name: "Skateboard", low: 3.0, med: 5.0, high: 6.5 },
  { name: "Skiroll", low: 5.0, med: 7.5, high: 10.5 },
  { name: "Snowboard", low: 4.0, med: 5.5, high: 7.5 },
  { name: "Softabll", low: 3.0, med: 4.0, high: 5.0 },
  { name: "Spinning", low: 5.0, med: 7.5, high: 10.0 },
  { name: "Squash", low: 5.5, med: 8.5, high: 12.0 },
  { name: "Subir escaleras", low: 4.0, med: 8.0, high: 12.0 },
  { name: "Surf", low: 3.0, med: 5.0, high: 7.5 },
  { name: "Surf de remo", low: 3.5, med: 6.0, high: 8.5 },
  { name: "Tenis", low: 4.5, med: 6.5, high: 8.5 },
  { name: "Tenis de mesa", low: 2.5, med: 4.0, high: 5.5 },
  { name: "Trineo", low: 4.0, med: 6.0, high: 8.0 },
  { name: "Trote", low: 5.5, med: 8.0, high: 10.5 },
  { name: "Vela", low: 2.5, med: 4.0, high: 6.0 },
  { name: "Voleibol", low: 3.0, med: 4.0, high: 6.0 },
  { name: "Voleibol de playa", low: 4.0, med: 6.0, high: 8.0 },
  { name: "Voleibol de interiores", low: 3.0, med: 4.0, high: 6.0 },
  { name: "Wakeboard", low: 4.0, med: 5.5, high: 7.5 },
  { name: "Windsurf", low: 4.5, med: 6.5, high: 8.5 },
  { name: "Yoga", low: 2.0, med: 3.0, high: 4.0 },
  { name: "Zumba", low: 4.0, med: 6.5, high: 8.5 },
];

export const STREAK_FAQ = [
  {
    q: "¿Qué es la racha y cómo se mide?",
    a: "La Racha de Actividad ayuda a mantener tu constancia física a largo plazo. En lugar de evaluar día a día, la app calcula un promedio ponderado de 7 días de tu actividad física (caminar, correr, gimnasio, etc.), donde las actividades más recientes tienen mayor peso.",
  },
  {
    q: "¿Cómo se mantiene y cuándo se pierde?",
    a: "Para mantener tu racha, tu promedio de 7 días debe estar en el nivel Saludable (150 Puntos o más). Si cae por debajo de este límite, tu racha vuelve a cero. No obstante, ¡se permite descansar! Si te saltas un día pero tu promedio sigue arriba de 150, tu racha no se romperá.",
  },
  {
    q: "¿Qué es la Curva de Actividad y la Línea Base?",
    a: "La Curva de Actividad grafica tu promedio de Puntos de Actividad de los últimos 7 días. La Línea Base Saludable (150 puntos) combina las pautas de actividad física diaria de la Organización Mundial de la Salud (OMS) con el MET.",
  },
  {
    q: "¿Cómo se calculan los Puntos de Actividad?",
    a: "Los puntos diarios son el promedio ponderado de los minutos MET. El MET (Equivalente Metabólico) mide la energía que consume una actividad comparada con el reposo. Los minutos MET de cada ejercicio se calculan multiplicando el valor MET de la actividad (según su intensidad) por los minutos entrenados.",
  },
];
